# 构建阶段
FROM node:24-alpine AS builder

WORKDIR /app

# 复制 package 文件
COPY package.json pnpm-lock.yaml ./

# 安装 pnpm
RUN npm install -g pnpm

# 安装依赖
# 使用 --no-frozen-lockfile 允许在 lockfile 不同步时自动更新
RUN pnpm install --no-frozen-lockfile

# 复制源代码
COPY . .

# 构建参数 - 用于传递环境变量
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_IBKR_API_URL
ARG VITE_IBKR_API_KEY
ARG VITE_HYPERLIQUID_TRADER_API_URL
ARG VITE_HYPERLIQUID_TRADER_API_KEY
ARG VITE_CRAWL4AI_API_URL
ARG VITE_CRAWL4AI_SECRET_KEY
ARG VITE_CF_ACCESS_CLIENT_ID
ARG VITE_CF_ACCESS_CLIENT_SECRET
ARG VITE_ALLOW_SIGNUP
ARG VITE_ALLOW_FORGOT_PASSWORD
ARG VITE_NEBULA_DEEP_RESEARCH_API_URL
ARG VITE_NEBULA_DEEP_RESEARCH_TOKEN
ARG VITE_IBKR_ACCOUNT_ID
ARG VITE_HUOHUO_API_URL
ARG VITE_MANMAN_API_URL
ARG VITE_OPENAI_BASE_URL
ARG VITE_OPENAI_API_KEY
ARG VITE_OPENAI_MODEL

# 设置环境变量（构建时需要）
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_IBKR_API_URL=$VITE_IBKR_API_URL
ENV VITE_IBKR_API_KEY=$VITE_IBKR_API_KEY
ENV VITE_IBKR_ACCOUNT_ID=$VITE_IBKR_ACCOUNT_ID
ENV VITE_HYPERLIQUID_TRADER_API_URL=$VITE_HYPERLIQUID_TRADER_API_URL
ENV VITE_HYPERLIQUID_TRADER_API_KEY=$VITE_HYPERLIQUID_TRADER_API_KEY
ENV VITE_CRAWL4AI_API_URL=$VITE_CRAWL4AI_API_URL
ENV VITE_CRAWL4AI_SECRET_KEY=$VITE_CRAWL4AI_SECRET_KEY
ENV VITE_CF_ACCESS_CLIENT_ID=$VITE_CF_ACCESS_CLIENT_ID
ENV VITE_CF_ACCESS_CLIENT_SECRET=$VITE_CF_ACCESS_CLIENT_SECRET
ENV VITE_ALLOW_SIGNUP=$VITE_ALLOW_SIGNUP
ENV VITE_ALLOW_FORGOT_PASSWORD=$VITE_ALLOW_FORGOT_PASSWORD
ENV VITE_NEBULA_DEEP_RESEARCH_API_URL=$VITE_NEBULA_DEEP_RESEARCH_API_URL
ENV VITE_NEBULA_DEEP_RESEARCH_TOKEN=$VITE_NEBULA_DEEP_RESEARCH_TOKEN
ENV VITE_HUOHUO_API_URL=$VITE_HUOHUO_API_URL
ENV VITE_MANMAN_API_URL=$VITE_MANMAN_API_URL
ENV VITE_OPENAI_BASE_URL=$VITE_OPENAI_BASE_URL
ENV VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY
ENV VITE_OPENAI_MODEL=$VITE_OPENAI_MODEL

# 构建应用
RUN pnpm run build

# 生产阶段 - 使用 nginx
FROM nginx:1.27-alpine

# 复制构建产物到 nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# 复制 nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 暴露端口
EXPOSE 80

# 启动 nginx
CMD ["nginx", "-g", "daemon off;"]

