/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedFinanceRouteRouteImport } from './routes/_authenticated/finance/route'
import { Route as AuthenticatedBeetraderRouteRouteImport } from './routes/_authenticated/beetrader/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedBeetraderIndexRouteImport } from './routes/_authenticated/beetrader/index'
import { Route as AuthenticatedBeeaiIndexRouteImport } from './routes/_authenticated/beeai/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedBeetraderStrategiesRouteImport } from './routes/_authenticated/beetrader/strategies'
import { Route as AuthenticatedBeetraderSignalsRouteImport } from './routes/_authenticated/beetrader/signals'
import { Route as AuthenticatedBeetraderMonitorObservationRouteImport } from './routes/_authenticated/beetrader/monitor-observation'
import { Route as AuthenticatedBeetraderMonitorRouteImport } from './routes/_authenticated/beetrader/monitor'
import { Route as AuthenticatedBeetraderBacktestRouteImport } from './routes/_authenticated/beetrader/backtest'
import { Route as AuthenticatedMonitoringTasksIndexRouteImport } from './routes/_authenticated/monitoring/tasks/index'
import { Route as AuthenticatedFinanceStatisticsIndexRouteImport } from './routes/_authenticated/finance/statistics/index'
import { Route as AuthenticatedFinanceExpensesIndexRouteImport } from './routes/_authenticated/finance/expenses/index'
import { Route as AuthenticatedFinanceExchangeRateIndexRouteImport } from './routes/_authenticated/finance/exchange-rate/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceRouteRoute =
  AuthenticatedFinanceRouteRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBeetraderRouteRoute =
  AuthenticatedBeetraderRouteRouteImport.update({
    id: '/beetrader',
    path: '/beetrader',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBeetraderIndexRoute =
  AuthenticatedBeetraderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBeetraderRouteRoute,
  } as any)
const AuthenticatedBeeaiIndexRoute = AuthenticatedBeeaiIndexRouteImport.update({
  id: '/beeai/',
  path: '/beeai/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBeetraderStrategiesRoute =
  AuthenticatedBeetraderStrategiesRouteImport.update({
    id: '/strategies',
    path: '/strategies',
    getParentRoute: () => AuthenticatedBeetraderRouteRoute,
  } as any)
const AuthenticatedBeetraderSignalsRoute =
  AuthenticatedBeetraderSignalsRouteImport.update({
    id: '/signals',
    path: '/signals',
    getParentRoute: () => AuthenticatedBeetraderRouteRoute,
  } as any)
const AuthenticatedBeetraderMonitorObservationRoute =
  AuthenticatedBeetraderMonitorObservationRouteImport.update({
    id: '/monitor-observation',
    path: '/monitor-observation',
    getParentRoute: () => AuthenticatedBeetraderRouteRoute,
  } as any)
const AuthenticatedBeetraderMonitorRoute =
  AuthenticatedBeetraderMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => AuthenticatedBeetraderRouteRoute,
  } as any)
const AuthenticatedBeetraderBacktestRoute =
  AuthenticatedBeetraderBacktestRouteImport.update({
    id: '/backtest',
    path: '/backtest',
    getParentRoute: () => AuthenticatedBeetraderRouteRoute,
  } as any)
const AuthenticatedMonitoringTasksIndexRoute =
  AuthenticatedMonitoringTasksIndexRouteImport.update({
    id: '/monitoring/tasks/',
    path: '/monitoring/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceStatisticsIndexRoute =
  AuthenticatedFinanceStatisticsIndexRouteImport.update({
    id: '/statistics/',
    path: '/statistics/',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)
const AuthenticatedFinanceExpensesIndexRoute =
  AuthenticatedFinanceExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)
const AuthenticatedFinanceExchangeRateIndexRoute =
  AuthenticatedFinanceExchangeRateIndexRouteImport.update({
    id: '/exchange-rate/',
    path: '/exchange-rate/',
    getParentRoute: () => AuthenticatedFinanceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/beetrader': typeof AuthenticatedBeetraderRouteRouteWithChildren
  '/finance': typeof AuthenticatedFinanceRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/beetrader/backtest': typeof AuthenticatedBeetraderBacktestRoute
  '/beetrader/monitor': typeof AuthenticatedBeetraderMonitorRoute
  '/beetrader/monitor-observation': typeof AuthenticatedBeetraderMonitorObservationRoute
  '/beetrader/signals': typeof AuthenticatedBeetraderSignalsRoute
  '/beetrader/strategies': typeof AuthenticatedBeetraderStrategiesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/beeai': typeof AuthenticatedBeeaiIndexRoute
  '/beetrader/': typeof AuthenticatedBeetraderIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/finance/exchange-rate': typeof AuthenticatedFinanceExchangeRateIndexRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesIndexRoute
  '/finance/statistics': typeof AuthenticatedFinanceStatisticsIndexRoute
  '/monitoring/tasks': typeof AuthenticatedMonitoringTasksIndexRoute
}
export interface FileRoutesByTo {
  '/finance': typeof AuthenticatedFinanceRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/beetrader/backtest': typeof AuthenticatedBeetraderBacktestRoute
  '/beetrader/monitor': typeof AuthenticatedBeetraderMonitorRoute
  '/beetrader/monitor-observation': typeof AuthenticatedBeetraderMonitorObservationRoute
  '/beetrader/signals': typeof AuthenticatedBeetraderSignalsRoute
  '/beetrader/strategies': typeof AuthenticatedBeetraderStrategiesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/beeai': typeof AuthenticatedBeeaiIndexRoute
  '/beetrader': typeof AuthenticatedBeetraderIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/finance/exchange-rate': typeof AuthenticatedFinanceExchangeRateIndexRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesIndexRoute
  '/finance/statistics': typeof AuthenticatedFinanceStatisticsIndexRoute
  '/monitoring/tasks': typeof AuthenticatedMonitoringTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/beetrader': typeof AuthenticatedBeetraderRouteRouteWithChildren
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/beetrader/backtest': typeof AuthenticatedBeetraderBacktestRoute
  '/_authenticated/beetrader/monitor': typeof AuthenticatedBeetraderMonitorRoute
  '/_authenticated/beetrader/monitor-observation': typeof AuthenticatedBeetraderMonitorObservationRoute
  '/_authenticated/beetrader/signals': typeof AuthenticatedBeetraderSignalsRoute
  '/_authenticated/beetrader/strategies': typeof AuthenticatedBeetraderStrategiesRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/beeai/': typeof AuthenticatedBeeaiIndexRoute
  '/_authenticated/beetrader/': typeof AuthenticatedBeetraderIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/finance/exchange-rate/': typeof AuthenticatedFinanceExchangeRateIndexRoute
  '/_authenticated/finance/expenses/': typeof AuthenticatedFinanceExpensesIndexRoute
  '/_authenticated/finance/statistics/': typeof AuthenticatedFinanceStatisticsIndexRoute
  '/_authenticated/monitoring/tasks/': typeof AuthenticatedMonitoringTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/beetrader'
    | '/finance'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/beetrader/backtest'
    | '/beetrader/monitor'
    | '/beetrader/monitor-observation'
    | '/beetrader/signals'
    | '/beetrader/strategies'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/beeai'
    | '/beetrader/'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/finance/exchange-rate'
    | '/finance/expenses'
    | '/finance/statistics'
    | '/monitoring/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/finance'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/beetrader/backtest'
    | '/beetrader/monitor'
    | '/beetrader/monitor-observation'
    | '/beetrader/signals'
    | '/beetrader/strategies'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/apps'
    | '/beeai'
    | '/beetrader'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/finance/exchange-rate'
    | '/finance/expenses'
    | '/finance/statistics'
    | '/monitoring/tasks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/beetrader'
    | '/_authenticated/finance'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/beetrader/backtest'
    | '/_authenticated/beetrader/monitor'
    | '/_authenticated/beetrader/monitor-observation'
    | '/_authenticated/beetrader/signals'
    | '/_authenticated/beetrader/strategies'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/beeai/'
    | '/_authenticated/beetrader/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/finance/exchange-rate/'
    | '/_authenticated/finance/expenses/'
    | '/_authenticated/finance/statistics/'
    | '/_authenticated/monitoring/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beetrader': {
      id: '/_authenticated/beetrader'
      path: '/beetrader'
      fullPath: '/beetrader'
      preLoaderRoute: typeof AuthenticatedBeetraderRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beetrader/': {
      id: '/_authenticated/beetrader/'
      path: '/'
      fullPath: '/beetrader/'
      preLoaderRoute: typeof AuthenticatedBeetraderIndexRouteImport
      parentRoute: typeof AuthenticatedBeetraderRouteRoute
    }
    '/_authenticated/beeai/': {
      id: '/_authenticated/beeai/'
      path: '/beeai'
      fullPath: '/beeai'
      preLoaderRoute: typeof AuthenticatedBeeaiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beetrader/strategies': {
      id: '/_authenticated/beetrader/strategies'
      path: '/strategies'
      fullPath: '/beetrader/strategies'
      preLoaderRoute: typeof AuthenticatedBeetraderStrategiesRouteImport
      parentRoute: typeof AuthenticatedBeetraderRouteRoute
    }
    '/_authenticated/beetrader/signals': {
      id: '/_authenticated/beetrader/signals'
      path: '/signals'
      fullPath: '/beetrader/signals'
      preLoaderRoute: typeof AuthenticatedBeetraderSignalsRouteImport
      parentRoute: typeof AuthenticatedBeetraderRouteRoute
    }
    '/_authenticated/beetrader/monitor-observation': {
      id: '/_authenticated/beetrader/monitor-observation'
      path: '/monitor-observation'
      fullPath: '/beetrader/monitor-observation'
      preLoaderRoute: typeof AuthenticatedBeetraderMonitorObservationRouteImport
      parentRoute: typeof AuthenticatedBeetraderRouteRoute
    }
    '/_authenticated/beetrader/monitor': {
      id: '/_authenticated/beetrader/monitor'
      path: '/monitor'
      fullPath: '/beetrader/monitor'
      preLoaderRoute: typeof AuthenticatedBeetraderMonitorRouteImport
      parentRoute: typeof AuthenticatedBeetraderRouteRoute
    }
    '/_authenticated/beetrader/backtest': {
      id: '/_authenticated/beetrader/backtest'
      path: '/backtest'
      fullPath: '/beetrader/backtest'
      preLoaderRoute: typeof AuthenticatedBeetraderBacktestRouteImport
      parentRoute: typeof AuthenticatedBeetraderRouteRoute
    }
    '/_authenticated/monitoring/tasks/': {
      id: '/_authenticated/monitoring/tasks/'
      path: '/monitoring/tasks'
      fullPath: '/monitoring/tasks'
      preLoaderRoute: typeof AuthenticatedMonitoringTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/statistics/': {
      id: '/_authenticated/finance/statistics/'
      path: '/statistics'
      fullPath: '/finance/statistics'
      preLoaderRoute: typeof AuthenticatedFinanceStatisticsIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
    '/_authenticated/finance/expenses/': {
      id: '/_authenticated/finance/expenses/'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AuthenticatedFinanceExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
    '/_authenticated/finance/exchange-rate/': {
      id: '/_authenticated/finance/exchange-rate/'
      path: '/exchange-rate'
      fullPath: '/finance/exchange-rate'
      preLoaderRoute: typeof AuthenticatedFinanceExchangeRateIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceRouteRoute
    }
  }
}

interface AuthenticatedBeetraderRouteRouteChildren {
  AuthenticatedBeetraderBacktestRoute: typeof AuthenticatedBeetraderBacktestRoute
  AuthenticatedBeetraderMonitorRoute: typeof AuthenticatedBeetraderMonitorRoute
  AuthenticatedBeetraderMonitorObservationRoute: typeof AuthenticatedBeetraderMonitorObservationRoute
  AuthenticatedBeetraderSignalsRoute: typeof AuthenticatedBeetraderSignalsRoute
  AuthenticatedBeetraderStrategiesRoute: typeof AuthenticatedBeetraderStrategiesRoute
  AuthenticatedBeetraderIndexRoute: typeof AuthenticatedBeetraderIndexRoute
}

const AuthenticatedBeetraderRouteRouteChildren: AuthenticatedBeetraderRouteRouteChildren =
  {
    AuthenticatedBeetraderBacktestRoute: AuthenticatedBeetraderBacktestRoute,
    AuthenticatedBeetraderMonitorRoute: AuthenticatedBeetraderMonitorRoute,
    AuthenticatedBeetraderMonitorObservationRoute:
      AuthenticatedBeetraderMonitorObservationRoute,
    AuthenticatedBeetraderSignalsRoute: AuthenticatedBeetraderSignalsRoute,
    AuthenticatedBeetraderStrategiesRoute:
      AuthenticatedBeetraderStrategiesRoute,
    AuthenticatedBeetraderIndexRoute: AuthenticatedBeetraderIndexRoute,
  }

const AuthenticatedBeetraderRouteRouteWithChildren =
  AuthenticatedBeetraderRouteRoute._addFileChildren(
    AuthenticatedBeetraderRouteRouteChildren,
  )

interface AuthenticatedFinanceRouteRouteChildren {
  AuthenticatedFinanceExchangeRateIndexRoute: typeof AuthenticatedFinanceExchangeRateIndexRoute
  AuthenticatedFinanceExpensesIndexRoute: typeof AuthenticatedFinanceExpensesIndexRoute
  AuthenticatedFinanceStatisticsIndexRoute: typeof AuthenticatedFinanceStatisticsIndexRoute
}

const AuthenticatedFinanceRouteRouteChildren: AuthenticatedFinanceRouteRouteChildren =
  {
    AuthenticatedFinanceExchangeRateIndexRoute:
      AuthenticatedFinanceExchangeRateIndexRoute,
    AuthenticatedFinanceExpensesIndexRoute:
      AuthenticatedFinanceExpensesIndexRoute,
    AuthenticatedFinanceStatisticsIndexRoute:
      AuthenticatedFinanceStatisticsIndexRoute,
  }

const AuthenticatedFinanceRouteRouteWithChildren =
  AuthenticatedFinanceRouteRoute._addFileChildren(
    AuthenticatedFinanceRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBeetraderRouteRoute: typeof AuthenticatedBeetraderRouteRouteWithChildren
  AuthenticatedFinanceRouteRoute: typeof AuthenticatedFinanceRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBeeaiIndexRoute: typeof AuthenticatedBeeaiIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedMonitoringTasksIndexRoute: typeof AuthenticatedMonitoringTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBeetraderRouteRoute:
    AuthenticatedBeetraderRouteRouteWithChildren,
  AuthenticatedFinanceRouteRoute: AuthenticatedFinanceRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBeeaiIndexRoute: AuthenticatedBeeaiIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedMonitoringTasksIndexRoute:
    AuthenticatedMonitoringTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
